services:
  app:
    build:
      context: .
      target: release
    container_name: app
    ports:
      - '8080:8080'
    env_file:
      - dev.env
    volumes:
      - ./config/dev.yml:/app/${CONFIG_PATH}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
