services:
  app:
    build:
      context: .
      target: release
    container_name: app
    ports:
      - '8080:8080'
    env_file:
      - dev.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/root/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    command: redis-server --requirepass ${REDIS_PASSWORD} --include /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ 'CMD', "redis-cli", "ping" ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  redis_config:
