env: "dev"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 10s

storage:
  postgres:
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: 10s
    conn_max_idle_time: 10s
