env: "local"

db:
  postgres:
    host: "localhost"
    port: 5432
    name: "go_pocket_link"
    ssl_mode: "disable"

auth:
  access_tok:
    expires_at: 10m
  refresh_tok:
    expires_at: 43200m